yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "@firebase/app-check-compat@*":
    peerDependencies:
      "@firebase/app": "0.x"
  "@firebase/analytics-compat@*":
    peerDependencies:
      "@firebase/app": "0.x"
  "@firebase/auth@*":
    peerDependencies:
      "@firebase/app-types": "0.x"
      "@firebase/util": "1.x"
  "@firebase/auth-compat@*":
    peerDependencies:
      "@firebase/app": "0.x"
      "@firebase/app-types": "0.x"
      "@firebase/util": "1.x"
  "@firebase/database@*":
    peerDependencies:
      "@firebase/app": "0.x"
      "@firebase/app-types": "0.x"
  "@firebase/database-compat@*":
    peerDependencies:
      "@firebase/app": "0.x"
      "@firebase/app-types": "0.x"
  "@firebase/firestore-compat@*":
    peerDependencies:
      "@firebase/app": "0.x"
      "@firebase/app-types": "0.x"
  "@firebase/functions@*":
    peerDependencies:
      "@firebase/app-types": "0.x"
  "@firebase/functions-compat@*":
    peerDependencies:
      "@firebase/app": "0.x"
      "@firebase/app-types": "0.x"
  "@firebase/messaging-compat@*":
    peerDependencies:
      "@firebase/app": "0.x"
  "@firebase/performance-compat@*":
    peerDependencies:
      "@firebase/app": "0.x"
  "@firebase/remote-config-compat@*":
    peerDependencies:
      "@firebase/app": "0.x"
  "@firebase/storage-compat@*":
    peerDependencies:
      "@firebase/app": "0.x"
      "@firebase/app-types": "0.x"
  "@preact/preset-vite@*":
    peerDependencies:
      preact: "*"
  "@linaria/shaker@*":
    peerDependencies:
      "@babel/plugin-proposal-export-namespace-from": "*"
  "vite-plugin-linaria@*":
    peerDependencies:
      "@babel/plugin-transform-modules-commonjs": "*"
      "@babel/plugin-proposal-export-namespace-from": "*"
  "vite-plugin-svgr@*":
    peerDependencies:
      "esbuild": "*"
