yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "@firebase/database@0.x":
    peerDependencies:
      "@firebase/app": "0.x"
      "@firebase/app-types": "0.x"
  "@firebase/auth@0.x":
    peerDependencies:
      "@firebase/app-types": "0.x"
      "@firebase/util": "1.x"
  "@preact/preset-vite@*":
    peerDependencies:
      preact: "*"
  "@linaria/shaker@*":
    peerDependencies:
      "@babel/plugin-proposal-export-namespace-from": "*"
  "vite-plugin-linaria@*":
    peerDependencies:
      "@babel/plugin-transform-modules-commonjs": "*"
      "@babel/plugin-proposal-export-namespace-from": "*"
