yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "@preact/preset-vite@*":
    peerDependencies:
      preact: "*"
  "@linaria/shaker@*":
    peerDependencies:
      "@babel/plugin-proposal-export-namespace-from": "*"
  "vite-plugin-linaria@*":
    peerDependencies:
      "@babel/plugin-transform-modules-commonjs": "*"
      "@babel/plugin-proposal-export-namespace-from": "*"
